### ISSUE TITLE
fix footer logo

### ISSUE THREAD

**Issue by aaryan182** [acicts/BITS22#10]
I want to fix the reponsivessnes of the footer replit logo

Plz assign this issue to me and add hacktoberfest label to it.

<img width="1030" alt="e1" src="https://user-images.githubusercontent.com/73265857/195249991-6958be16-3e8a-4da5-b6b8-4aa1d9d0832f.png">

**Comment by PasinduDushan** [comment]
Sure. Go ahead.

**Comment by aaryan182** [comment]
Please assign this issue to me .

**Comment by Hrx4** [comment]
hi sir, please assign this to me, i can solve the issue.

**Comment by PasinduDushan** [comment]
Sure @Hrx4 go ahead
