### ISSUE TITLE
Typo errors in Help page

### ISSUE THREAD

**Issue by senura-47802** [acicts/BITS22#19]
### **Found Grammatical and typo errors in Help page.**
![Screenshot (14)](https://user-images.githubusercontent.com/88277850/198868488-98e4bcdd-fc12-4e57-be47-87b60e85f69d.png)
There are some errors in last one .

**Comment by senura-47802** [comment]
Can I do the contributions and correct the errors.

**Comment by senura-47802** [comment]
@PasinduDushan can I make the contributions and correct the errors.

**Comment by PasinduDushan** [comment]
Sure. You can go ahead and correct the issues.
