### ISSUE TITLE
Adding floating animation to the robot like mascot

### ISSUE THREAD

**Issue by marsian83** [acicts/BITS22#3]
The mascot on the home page could really do with a little bit of floating animation , it'd fit the robotic style and also make the site come to life a lot more.

Please assign this task to me under hacktoberfest

**Comment by PasinduDushan** [comment]
Sure thing. I'm adding hacktoberfest label and once you do the pull request and if it shows good quality I'll accept and add the hacktoberfest-accepted label.

**Comment by jriyyya** [comment]
#4 implements this
@PasinduDushan consider merging this PR where I implemented this issue under ahcktoberfest

**Comment by minukag** [comment]
#4 merged!
